version: '3.2.1'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    image: kunalbarca/best-football-players_server
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    image: kunalbarca/best-football-players_client
    links:
      - "server:be"